- name: create release folder
  file: path={{web_dir}}/{{app_name}}/src/{{app_version}}/ state=directory owner={{ansible_user_id}}

- name: copy release files
  copy: src=../../bin/releases/{{app_version}}/linux_amd64/ dest={{web_dir}}/{{app_name}}/src/{{app_version}}/

- name: create current symlink to {{app_version}}
  file: src={{web_dir}}/{{app_name}}/src/{{app_version}} dest={{web_dir}}/{{app_name}}/current state=link

- name: create conf folder
  file: path={{web_dir}}/{{app_name}}/current/conf state=directory owner={{ansible_user_id}}

- name: copy .env file
  template: src=dot.env dest={{web_dir}}/{{app_name}}/current/.env

- name: create startup script
  sudo: yes
  template: src=upstart.conf dest=/etc/init/{{app_name}}.conf mode=644

- name: create nginx site config
  template: src=nginx.conf dest={{web_dir}}/{{app_name}}/current/conf/{{app_env}}-nginx.conf

- name: link ubuntu nginx site config
  sudo: yes
  file: src={{web_dir}}/{{app_name}}/current/conf/{{app_env}}-nginx.conf dest=/etc/nginx/sites-enabled/{{app_name}}-{{app_env}} state=link
  notify:
    - Restart nginx

- name: restart service
  command: service {{app_name}} restart
  sudo: yes
  when: app_env != 'dev'
  notify:
    - Restart nginx
